### ISSUE TITLE
don't use address 

### ISSUE THREAD

**Issue by vladimir-poopin** [HackerIndustrial-web3/Brownie-Starter-Kit#1]
the private key for address `0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1` was in your .env config

don't use this address ever again. 

just dropping this here in case you didn't realise you pushed it to github.

**Comment by deandunbar** [comment]
Appreciate you looking out!
I know about the priv key on there. It is the default generated from ganache-cli with the "-d" flag. I use it for localtesting but would never be used for real deployments.
